# Generated by Django 5.0.6 on 2024-05-25 00:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDasarST',
            fields=[
                ('kode_dasar', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('keterangan', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterGolongan',
            fields=[
                ('kode_golongan', models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('keterangan', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterJabatan',
            fields=[
                ('kode_jabatan', models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('keterangan', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('kode_permission', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterRole',
            fields=[
                ('kode_role', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('permissions', models.JSONField()),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrxSuratTugas',
            fields=[
                ('nomor_surat', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tgl_surat', models.DateField(null=True)),
                ('lokasi_surat', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=50)),
                ('lokasi', models.CharField(max_length=50)),
                ('tgl_awal_tugas', models.DateField(null=True)),
                ('tgl_akhir_tugas', models.DateField(null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('kepala_nama', models.CharField(blank=True, max_length=50, null=True)),
                ('kepala_nik', models.CharField(blank=True, max_length=50, null=True)),
                ('kepala_jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('kepala_golongan', models.CharField(blank=True, max_length=50, null=True)),
                ('submit', models.BooleanField(default=False)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPegawai',
            fields=[
                ('nik', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_kepala', models.BooleanField(default=False)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('kode_golongan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.mastergolongan')),
                ('kode_jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterjabatan')),
            ],
            options={
                'unique_together': {('is_kepala', 'nik', 'nama')},
            },
        ),
        migrations.CreateModel(
            name='ConfigDispenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_PLT', models.BooleanField(default=False)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('kepala', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterpegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterrole')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ST_Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterpegawai')),
                ('nomor_surat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas')),
            ],
            options={
                'unique_together': {('nomor_surat', 'peserta')},
            },
        ),
        migrations.CreateModel(
            name='ST_DasarTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=20, null=True)),
                ('dasar_tugas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterdasarst')),
                ('nomor_surat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas')),
            ],
            options={
                'unique_together': {('nomor_surat', 'dasar_tugas')},
            },
        ),
    ]
