# Generated by Django 5.0.6 on 2024-05-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterpegawai',
            unique_together={('is_kepala',)},
        ),
    ]
