# Generated by Django 5.0.6 on 2024-05-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0002_alter_masterpegawai_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='role',
        ),
    ]
