# Generated by Django 5.0.6 on 2024-05-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0003_remove_pengguna_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='is_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
