# Generated by Django 5.0.6 on 2024-05-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0004_pengguna_is_create_pengguna_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterpegawai',
            unique_together=set(),
        ),
    ]
