# Generated by Django 5.0.6 on 2024-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0005_alter_masterpegawai_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdispenda',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
