# Generated by Django 5.0.6 on 2024-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0007_logging'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='grouping',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
