# Generated by Django 5.0.6 on 2024-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0008_logging_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxsurattugas',
            name='is_plt',
            field=models.BooleanField(default=False),
        ),
    ]
