# Generated by Django 5.0.6 on 2024-06-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0009_trxsurattugas_is_plt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='st_dasartugas',
            old_name='nomor_surat',
            new_name='id_surat',
        ),
        migrations.RenameField(
            model_name='st_peserta',
            old_name='nomor_surat',
            new_name='id_surat',
        ),
        migrations.AddField(
            model_name='trxsurattugas',
            name='id_surat',
            field=models.CharField(default='', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trxsurattugas',
            name='nomor_surat',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='st_dasartugas',
            unique_together={('id_surat', 'dasar_tugas')},
        ),
        migrations.AlterUniqueTogether(
            name='st_peserta',
            unique_together={('id_surat', 'peserta')},
        ),
    ]
