# Generated by Django 5.0.6 on 2024-06-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0010_rename_nomor_surat_st_dasartugas_id_surat_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='st_dasartugas',
            unique_together=set(),
        ),
    ]
