# Generated by Django 5.0.6 on 2024-06-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0011_alter_st_dasartugas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='st_dasartugas',
            unique_together={('id_surat', 'dasar_tugas')},
        ),
    ]
