# Generated by Django 5.0.6 on 2024-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0015_alter_st_dasartugas_dasar_tugas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trxsurattugas',
            name='is_lhe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trxsurattugas',
            name='is_resume',
            field=models.BooleanField(default=False),
        ),
    ]
