# Generated by Django 5.0.6 on 2024-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0017_alter_trxsurattugas_id_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
