# Generated by Django 5.0.7 on 2024-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0018_alter_pengguna_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdasarst',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='mastergolongan',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='masterjabatan',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='masterpegawai',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='trxsurattugas',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
