# Generated by Django 5.0.7 on 2024-07-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0019_masterdasarst_is_new_mastergolongan_is_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterdasarst',
            old_name='is_new',
            new_name='is_update',
        ),
        migrations.RenameField(
            model_name='mastergolongan',
            old_name='is_new',
            new_name='is_update',
        ),
        migrations.RenameField(
            model_name='masterjabatan',
            old_name='is_new',
            new_name='is_update',
        ),
        migrations.RenameField(
            model_name='masterpegawai',
            old_name='is_new',
            new_name='is_update',
        ),
        migrations.RenameField(
            model_name='trxsurattugas',
            old_name='is_new',
            new_name='is_update',
        ),
    ]
