# Generated by Django 5.0.7 on 2024-07-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat_tugas', '0020_rename_is_new_masterdasarst_is_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdasarst',
            name='is_update',
        ),
        migrations.RemoveField(
            model_name='mastergolongan',
            name='is_update',
        ),
        migrations.RemoveField(
            model_name='masterjabatan',
            name='is_update',
        ),
    ]
