# Generated by Django 5.0.6 on 2024-06-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surat_tugas', '0015_alter_st_dasartugas_dasar_tugas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrxLHE',
            fields=[
                ('id_lhe', models.CharField(default='95de4fb9-d581-4f8c-98c2-6ff581c4298d', max_length=16, primary_key=True, serialize=False)),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('suratTugas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas')),
            ],
        ),
    ]
