# Generated by Django 5.0.6 on 2024-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxlhe',
            name='id_lhe',
            field=models.CharField(default='c72164f3-2819-4966-9dc2-053912ac8f97', max_length=36, primary_key=True, serialize=False),
        ),
    ]
