# Generated by Django 5.0.6 on 2024-06-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0003_alter_trxlhe_id_lhe'),
        ('surat_tugas', '0015_alter_st_dasartugas_dasar_tugas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='headerLHE',
            fields=[
                ('id_lhe', models.CharField(default='e74388f0-fb99-4be6-8346-6fd0932e3a13', max_length=36, primary_key=True, serialize=False)),
                ('nomor_lhe', models.CharField(max_length=50, unique=True)),
                ('tanggal_lhe', models.DateField(blank=True, null=True)),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('suratTugas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas')),
            ],
        ),
        migrations.CreateModel(
            name='dataumumLHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200)),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.DeleteModel(
            name='TrxLHE',
        ),
    ]
