# Generated by Django 5.0.6 on 2024-06-10 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0004_headerlhe_dataumumlhe_delete_trxlhe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='ae32f6f1-df6d-4ea5-a84d-07aac854736c', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='kepegawaianLHE',
            fields=[
                ('id_kepegawaian', models.CharField(default='<function uuid4 at 0x0000018D09239120>', max_length=36, primary_key=True, serialize=False)),
                ('data_bulan', models.DateField()),
                ('review', models.CharField(default='b.\tPengelolaan administrasi kepegawaian sudah dilaksanakan dengan baik dan tertib.', max_length=100)),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
        migrations.CreateModel(
            name='detailNormatifPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=100, verbose_name='Nama Pegawai')),
                ('nip', models.CharField(default='', max_length=50, verbose_name='NIP Pegawai')),
                ('jabatan', models.CharField(default='', max_length=50, verbose_name='Nama Jabatan')),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_kepegawaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.kepegawaianlhe')),
            ],
        ),
        migrations.CreateModel(
            name='simpulanPegawaiLHE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(default='', max_length=20, verbose_name='Jenis Pegawai')),
                ('jumlah', models.SmallIntegerField(default=0, verbose_name='Jumlah Pegawai')),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_kepegawaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.kepegawaianlhe')),
            ],
        ),
    ]
