# Generated by Django 5.0.6 on 2024-06-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0005_alter_headerlhe_id_lhe_kepegawaianlhe_and_more'),
        ('surat_tugas', '0015_alter_st_dasartugas_dasar_tugas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlhe',
            name='submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='477b5393-5eca-4559-ab1b-9fd97236da0c', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headerlhe',
            name='nomor_lhe',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nomor Laporan Hasil Evaluasi'),
        ),
        migrations.AlterField(
            model_name='headerlhe',
            name='suratTugas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas', verbose_name='Acuan Surat Tugas'),
        ),
        migrations.AlterField(
            model_name='headerlhe',
            name='tanggal_lhe',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Laporan Hasil Evaluasi'),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x00000198AF389120>', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='headerlhe',
            unique_together={('nomor_lhe', 'suratTugas')},
        ),
    ]
