# Generated by Django 5.0.6 on 2024-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0006_headerlhe_submit_alter_headerlhe_id_lhe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='bdd730c3-a6fc-4643-b869-139e651440d7', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x000002459A489120>', max_length=36, primary_key=True, serialize=False),
        ),
    ]
