# Generated by Django 5.0.6 on 2024-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0014_alter_headerlhe_id_lhe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='260343995.17733598', max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x000002073DC49120>', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='5adabba5-d589-4a57-8c83-efaa6c3015b9', max_length=36, primary_key=True, serialize=False),
        ),
    ]
