# Generated by Django 5.0.6 on 2024-06-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0017_headerlhe_periode_akhir_headerlhe_periode_awal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kepegawaianlhe',
            name='id_lhe',
        ),
        migrations.RemoveField(
            model_name='simpulanpegawailhe',
            name='id_kepegawaian',
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='3b8c1b27-e138-4cc7-bd66-328aac9a6160', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='d5a71bb8-6219-4748-922c-f6582bf02a1a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='9de06acc-ad4f-4e9f-acda-f6cb062ec01e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab2_data_umum',
            fields=[
                ('id_data_umum', models.CharField(default='ccb170ad-ab81-4271-a371-e4e73ab5ae18', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_kepegawaian',
            fields=[
                ('id_tu_kepegawaian', models.CharField(default='afc2e122-0bf1-4eb0-851f-08499d9773e3', max_length=36, primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=20)),
                ('UPPD', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_kepegawaian_detail',
            fields=[
                ('id_tu_kepegawaian_detail', models.CharField(default='1fec57d4-16ec-4eaa-a9a1-28f015797160', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField(default=0)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_kepegawaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_kepegawaian')),
            ],
        ),
        migrations.DeleteModel(
            name='detailNormatifPegawai',
        ),
        migrations.DeleteModel(
            name='kepegawaianLHE',
        ),
        migrations.DeleteModel(
            name='simpulanPegawaiLHE',
        ),
    ]
