# Generated by Django 5.0.6 on 2024-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0023_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_keuangan',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='597c04db-c8b0-4b5a-9de6-0202da8d83fa', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='b49662bf-d865-464f-a5e3-d61f72e32423', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='72093a5e-e3d2-49c7-8848-87618eb9632b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='c8b19f06-b4d6-4dd9-b714-a3c740060233', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='e8bf0c08-9a29-4ba3-bb34-a6b7cc1501b6', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='71c86e54-337f-477e-8601-d92fb8513bfa', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='0f1a08e5-469c-44ae-b1c4-da548658f735', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='7e94352c-d942-499d-95d1-a60e21f73f97', max_length=36, primary_key=True, serialize=False),
        ),
    ]
