# Generated by Django 5.0.6 on 2024-06-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0024_alter_bab2_tatausaha_keuangan_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='6947f2da-6179-4f75-beab-40ddf7e38c63', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='23425182-0093-4a61-b589-a8433b60d952', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='d9450ac1-46b4-4bd1-84bc-d61c377775e6', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='fd1d5a18-a34e-427a-bc15-f920028323ab', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='a6683a4a-5a94-4d92-b84e-3cdaf45a2e95', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='4d2b2e75-0d7f-4bd0-b1a1-77bf2c280bc9', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='a4366c5e-45ad-4243-a296-4a525ee3e63a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='8a205c96-f1c3-42ea-8f89-354d3673e484', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_bangun_tanah',
            fields=[
                ('id_tu_bagun_tanah', models.CharField(default='aa717725-029f-459d-939a-e5f26398185b', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_keuangan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_keuangan')),
            ],
            options={
                'unique_together': {('id_tu_keuangan', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_keuangan_a_tg',
            fields=[
                ('id_tu_a_tg', models.CharField(default='16c43284-41fa-4e6a-aa2c-babdc7fc2ee0', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_keuangan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_keuangan')),
            ],
            options={
                'unique_together': {('id_tu_keuangan', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_mobil_pemkab',
            fields=[
                ('id_tu_mobil_pemkab', models.CharField(default='cc041a23-06e9-4708-8599-763a85fd702d', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_keuangan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_keuangan')),
            ],
            options={
                'unique_together': {('id_tu_keuangan', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_mobil_pemprov',
            fields=[
                ('id_tu_mobil_pemprov', models.CharField(default='5dfe30de-7b98-4fa0-b9eb-050dbde1d3f5', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_keuangan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_keuangan')),
            ],
            options={
                'unique_together': {('id_tu_keuangan', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_motor_pemprov',
            fields=[
                ('id_tu_motor_pemprov', models.CharField(default='42c4b97b-64db-41c9-97b8-837034811bd1', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_keuangan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_keuangan')),
            ],
            options={
                'unique_together': {('id_tu_keuangan', 'detail')},
            },
        ),
    ]
