# Generated by Django 5.0.6 on 2024-06-27 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0026_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_bangun_tanah',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_mobil_pemkab',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_mobil_pemprov',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_motor_pemprov',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AddField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_lhe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_lhe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_lhe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_lhe',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='c1fdaf9c-0a47-4c47-99f4-8e876e5a0b3e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='21c55198-0e92-405c-9d6b-ea3114ac8c3d', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='5b3cac3b-8f0c-42fb-b727-2d70a13cc473', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='5081fdac-c4e9-4539-aa2e-cfc131d520b3', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='b41dc839-c4e8-4278-a100-588c394446ac', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='cb74ecb2-53d4-436a-9e4f-8c1e89d136e5', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='e3ef4dec-5e29-4bb6-84ac-fef720dcc75a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan_a_tg',
            name='id_tu_a_tg',
            field=models.CharField(default='bf62b616-d1b5-48fc-9d4b-7cfc53e5c9b2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan_a_tg',
            name='id_tu_keuangan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe'),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='7c3cf0e9-47df-4154-949a-05a52d7ef9bc', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='fbe4cbed-c024-4a7e-9986-4f2c353c09d9', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='44d07e1d-886f-4f46-956b-986687dc841a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='57b10e5a-10b2-4d6d-9c2a-3dded2d93bff', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='955db4bb-0a61-4202-8293-171cdd60adaf', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_keuangan',
        ),
        migrations.RemoveField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_keuangan',
        ),
        migrations.RemoveField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_keuangan',
        ),
        migrations.RemoveField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_keuangan',
        ),
    ]
