# Generated by Django 5.0.6 on 2024-06-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0027_alter_bab2_tatausaha_bangun_tanah_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='3e410245-63b1-440b-8ec5-bc61a85a152b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='7d84e971-7025-4ef0-8684-29cbf5ca536e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='dcd173dc-3d1a-4985-a514-ab30a5362a4f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='d2bbd2ca-2fcf-4282-8e7c-6fab4d75ae77', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='fdf02add-9434-49fd-a447-ec53a6263615', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='a9700bf1-9b98-44c7-b0b6-4fcf1c56dbb8', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='4f55268d-0f24-4a2b-9ae4-f67cb49e4f9b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan_a_tg',
            name='id_tu_a_tg',
            field=models.CharField(default='289712c1-80ba-40fc-a0b2-5f9a9783c0f9', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='1cb1cc13-8c78-44f5-8ce4-f0cf987c6300', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='9ee98d9f-1cd3-4bf0-af56-21233839fb71', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='d3cac503-7c6b-43c9-876e-d4f708a2809e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='92da603c-88fc-4c05-afbc-58595442da07', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='bfa0d5c9-9626-4886-8f04-e0acc320e6d8', max_length=36, primary_key=True, serialize=False),
        ),
    ]
