# Generated by Django 5.0.6 on 2024-06-27 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surat_tugas', '0017_alter_trxsurattugas_id_surat'),
    ]

    operations = [
        migrations.CreateModel(
            name='headerLHE',
            fields=[
                ('id_lhe', models.CharField(default='', max_length=11, primary_key=True, serialize=False)),
                ('nomor_lhe', models.CharField(max_length=50, unique=True, verbose_name='Nomor Laporan Hasil Evaluasi')),
                ('tanggal_lhe', models.DateField(blank=True, null=True, verbose_name='Tanggal Laporan Hasil Evaluasi')),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('submit', models.BooleanField(default=False)),
                ('periode_awal', models.DateField(blank=True, null=True)),
                ('periode_akhir', models.DateField(blank=True, null=True)),
                ('suratTugas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas', verbose_name='Acuan Surat Tugas')),
            ],
            options={
                'unique_together': {('nomor_lhe', 'suratTugas')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_kepegawaian',
            fields=[
                ('id_tu_kepegawaian', models.CharField(default='de97631e-e2a5-4143-9e7a-3cef3c2ca0ab', max_length=36, primary_key=True, serialize=False)),
                ('periode', models.CharField(max_length=20)),
                ('UPPD', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_kepegawaian_detail',
            fields=[
                ('id_tu_kepegawaian_detail', models.CharField(default='42c18715-a338-4e86-b12c-b12d1a840f6b', max_length=36, primary_key=True, serialize=False)),
                ('golongan', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField(default=0)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_kepegawaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_kepegawaian')),
            ],
            options={
                'unique_together': {('id_tu_kepegawaian', 'golongan')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_kepegawaian_normatif',
            fields=[
                ('id_tu_kepegawaian_normatif', models.CharField(default='4fdde54b-5ff7-4ade-b3fb-95d78ad2dfa7', max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_kepegawaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_kepegawaian')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterjabatan')),
            ],
            options={
                'unique_together': {('id_tu_kepegawaian', 'nama', 'nip')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tujuan_evaluasi_pembinaan',
            fields=[
                ('id_tujuan', models.CharField(default='f4352c2a-538d-4b77-abdf-bf88634c5408', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_motor_pemprov',
            fields=[
                ('id_tu_motor_pemprov', models.CharField(default='83faaaeb-54c6-4940-817c-df941e6a2434', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_mobil_pemprov',
            fields=[
                ('id_tu_mobil_pemprov', models.CharField(default='80184ac4-a5fc-4a3e-9d4b-afb28901ad2b', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_mobil_pemkab',
            fields=[
                ('id_tu_mobil_pemkab', models.CharField(default='5831993a-e6a8-4d09-aa17-4d14301f8504', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_keuangan',
            fields=[
                ('id_tu_keuangan', models.CharField(default='9f31e0cf-0398-4b35-96ef-4eaf5fa6eafd', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_bangun_tanah',
            fields=[
                ('id_tu_bagun_tanah', models.CharField(default='da349523-1210-4376-afac-d7e58ff29088', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_sasaran_evaluasi_pembinaan',
            fields=[
                ('id_sasaran', models.CharField(default='5886f8b7-f6c5-468d-a629-dc5d2fbaf274', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='bab2_data_umum',
            fields=[
                ('id_data_umum', models.CharField(default='83c572fc-17c6-4af7-b7b7-8686c45edea5', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
        migrations.CreateModel(
            name='simpulanHasilValBin',
            fields=[
                ('id_simpulan', models.CharField(default='0a9fe55b-cf0b-4096-858f-f6b1cf56e8cb', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_lhe', 'detail')},
            },
        ),
    ]
