# Generated by Django 5.0.6 on 2024-06-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0002_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='4cefa64d-9bb3-4a25-a462-4ad4798c20dc', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='39b74a9d-9de5-48d9-9a29-3b81737193af', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='73655741-ecd9-47a9-a236-66344dc95e67', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='dd5d3e50-981e-49ad-9977-8a7c1766aed0', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='d8a322af-a941-4153-9a06-2f579618a5f2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='d23a98c1-d241-46c6-bc76-5df5c5e08bee', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='5ab097b8-d99c-4762-ba67-fc161fb7a06e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='fe5a79ed-066d-4bbf-a0ef-fb8ac20b1510', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='41a261e1-b54e-4ffa-ad48-cf20ca3e9bc4', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='e88008b3-8995-4288-9f75-05cfc0613108', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='29da4d52-3ed3-4420-be19-ceb3bad5d2ae', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='17b11c39-4447-4bb1-81b6-2c2237894b59', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab3_pkb',
            fields=[
                ('id_pkb', models.CharField(default='<function uuid4 at 0x000001F2A2702700>', max_length=36, primary_key=True, serialize=False)),
                ('bulan_awal', models.SmallIntegerField(choices=[(1, 'JANUARI'), (2, 'FEBRUARI'), (3, 'MARET'), (4, 'APRIL'), (5, 'MEI'), (6, 'JUNI'), (7, 'JULI'), (8, 'AGUSTUS'), (9, 'SEPTEMBER'), (10, 'OKTOBER'), (11, 'NOVEMBER'), (12, 'DESEMBER')], default=1)),
                ('bulan_akhir', models.SmallIntegerField(choices=[(1, 'JANUARI'), (2, 'FEBRUARI'), (3, 'MARET'), (4, 'APRIL'), (5, 'MEI'), (6, 'JUNI'), (7, 'JULI'), (8, 'AGUSTUS'), (9, 'SEPTEMBER'), (10, 'OKTOBER'), (11, 'NOVEMBER'), (12, 'DESEMBER')], default=12)),
                ('tahun_awal', models.IntegerField(default=2024)),
                ('tahun_akhir', models.IntegerField(default=2024)),
                ('uppd', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=200)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
    ]
