# Generated by Django 5.0.6 on 2024-06-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0004_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bab3_pkb',
            name='selisih_angka',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bab3_pkb',
            name='selisih_persen',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='2ab87f0e-a9d8-4934-84f9-2232470f592a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='fa033fe2-f384-4e01-b4a7-957858ee08e9', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='60deea57-edc1-408f-8337-be1d27c1cd5e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='3baa2c28-4530-4fa5-9451-09e055b5a817', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='cbe97a09-ab71-4f22-ba4d-cdf4a04ce4a9', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='adf10900-8b5b-48a7-bac8-2b1bfc1612c1', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='1020c86c-1965-4b8e-bc47-4fe6a25f0bb0', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='1afc687b-cda9-4536-83dd-7350bf353841', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='66f94f3f-a382-4242-a82c-77ca98fe36ea', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='4d90e09e-3aee-4bc2-b028-491bbcc9cc4e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='86736c70-8c68-45f7-9f9a-a6c57b176f58', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='bulan_akhir',
            field=models.PositiveSmallIntegerField(choices=[(1, 'JANUARI'), (2, 'FEBRUARI'), (3, 'MARET'), (4, 'APRIL'), (5, 'MEI'), (6, 'JUNI'), (7, 'JULI'), (8, 'AGUSTUS'), (9, 'SEPTEMBER'), (10, 'OKTOBER'), (11, 'NOVEMBER'), (12, 'DESEMBER')], default=12),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='bulan_awal',
            field=models.PositiveSmallIntegerField(choices=[(1, 'JANUARI'), (2, 'FEBRUARI'), (3, 'MARET'), (4, 'APRIL'), (5, 'MEI'), (6, 'JUNI'), (7, 'JULI'), (8, 'AGUSTUS'), (9, 'SEPTEMBER'), (10, 'OKTOBER'), (11, 'NOVEMBER'), (12, 'DESEMBER')], default=1),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='id_pkb',
            field=models.CharField(default='16fd8f76-59f9-4aa1-85c9-d8a4fbc0f28c', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='tahun_akhir',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='tahun_awal',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='6d523b50-0a34-4e6e-9705-6bf0fe0a815a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab3_pkb_detail',
            fields=[
                ('id_pkb_detail', models.CharField(default='0fed77ff-8ba4-4a26-b15e-f4d75909a219', max_length=36, primary_key=True, serialize=False)),
                ('bulan', models.PositiveSmallIntegerField(choices=[(1, 'JANUARI'), (2, 'FEBRUARI'), (3, 'MARET'), (4, 'APRIL'), (5, 'MEI'), (6, 'JUNI'), (7, 'JULI'), (8, 'AGUSTUS'), (9, 'SEPTEMBER'), (10, 'OKTOBER'), (11, 'NOVEMBER'), (12, 'DESEMBER')], default=1)),
                ('tahun_awal', models.PositiveSmallIntegerField(default=2024)),
                ('tahun_akhir', models.PositiveSmallIntegerField(default=2024)),
                ('nilai_awal', models.BigIntegerField(default=0)),
                ('nilai_akhir', models.BigIntegerField(default=0)),
                ('selisih_angka', models.BigIntegerField(blank=True, default=0, null=True)),
                ('selisih_persen', models.FloatField(blank=True, default=0.0, null=True)),
                ('id_pkb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab3_pkb')),
            ],
        ),
    ]
