# Generated by Django 5.0.6 on 2024-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0005_bab3_pkb_selisih_angka_bab3_pkb_selisih_persen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bab3_pkb',
            name='createdAt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bab3_pkb',
            name='createdBy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bab3_pkb_detail',
            name='createdAt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bab3_pkb_detail',
            name='createdBy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='e1e258d1-9f5b-4bc6-a014-2605e1c69667', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='51bc5f5b-13e8-48aa-9260-d5f4b79462e4', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='5bb50ba9-b3b9-4c89-a91b-65710e60eef6', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='9e5a65e6-e6ee-4b6c-a763-c72af83ed1b7', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='7b3393e4-1156-4454-b05f-287619e08b03', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='72211bca-8c4a-418c-9636-8f7d8e11ee98', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='937f7000-db62-42d9-873b-3ed4e09ce989', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='5fa6c34e-c142-4b4b-b527-d66a86302632', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='bc6572a0-02ba-4590-a2d0-ac5603406a87', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='aa894978-9d25-4a14-a940-c6bdd4c78391', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='72bf4b57-2960-4071-9e80-9e2ff605b6dc', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='id_pkb',
            field=models.CharField(default='593458aa-fd74-4677-b22f-96c440b974bf', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb_detail',
            name='id_pkb_detail',
            field=models.CharField(default='ae5d8a1e-9a83-4bd3-afe7-f7ae275984a2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='808efe7e-c85e-4203-bba1-1d7aacab6296', max_length=36, primary_key=True, serialize=False),
        ),
    ]
