# Generated by Django 5.0.6 on 2024-06-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0006_bab3_pkb_createdat_bab3_pkb_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bab3_pkb',
            name='is_periode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='bbd64223-e802-4e10-bebc-98c8af8832bd', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='0572f3e4-d2b4-436a-9575-f19a97c34a05', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='c2de6b53-bbdb-4585-8c3d-bdc6d2fd234f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='753a0eda-604f-4e26-9a8b-eddaea12e4aa', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='eee8d367-16c1-4f1a-afa0-1fcf2e4b00b6', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='113d45f1-73c1-4afc-b478-e1a2d31fc85f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='09408dcc-f7d6-4d50-8a1d-dcd0147405f3', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='d523ceae-5c08-431b-99ee-be797a7c6917', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='7f145115-bc3b-4fdd-b128-5d2e0d4ca4d3', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='51d141cc-eb25-473c-9ba9-67fed9bfb8dc', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='3d49ebd0-9a71-4d5a-a2b1-6d66a2939476', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='id_pkb',
            field=models.CharField(default='f7624bbb-07dd-4194-9be9-584e26a13fbc', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb_detail',
            name='id_pkb_detail',
            field=models.CharField(default='2ab0a567-bded-4688-a76a-fa197cc1365b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='28d7b4d8-de3e-4b60-b622-4b678d6f6da0', max_length=36, primary_key=True, serialize=False),
        ),
    ]
