# Generated by Django 5.0.6 on 2024-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0008_alter_headerlhe_id_lhe_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dataumumLHE',
            new_name='simpulanHasilValBin',
        ),
        migrations.AlterUniqueTogether(
            name='simpulanhasilvalbin',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='262ec6f3-df56-46fd-bcd5-2028a5b1c87f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x000002405E0F9120>', max_length=36, primary_key=True, serialize=False),
        ),
    ]
