# Generated by Django 5.0.6 on 2024-06-13 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0009_rename_dataumumlhe_simpulanhasilvalbin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpulanhasilvalbin',
            name='id',
        ),
        migrations.AddField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default=uuid.UUID('dbaac671-b931-4487-9ead-1e9ed2668db8'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='1e95e5f2-9f35-4dda-a5a6-c8448ec4db76', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x0000018EB92D9120>', max_length=36, primary_key=True, serialize=False),
        ),
    ]
