# Generated by Django 5.0.6 on 2024-06-13 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0010_remove_simpulanhasilvalbin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='d4bd5d4d-4b1d-4f3d-ac36-238c512f331a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x000001A0F5BB9120>', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default=uuid.UUID('f6d20118-09ca-4c48-ab1b-1cb9a6b30e1d'), max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='simpulanhasilvalbin',
            unique_together={('id_lhe', 'id_simpulan')},
        ),
    ]
