# Generated by Django 5.0.6 on 2024-06-13 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0012_alter_simpulanhasilvalbin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='54ef5758-3c39-4901-a76e-3aab9e58fe4d', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x0000020ED6589120>', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default=uuid.UUID('7ea87974-350e-4bef-aaf1-12678a618f76'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
