# Generated by Django 5.0.6 on 2024-07-03 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0013_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='jml_pkb_hitam',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='jml_pkb_kuning',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='jml_pkb_roda4',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='obj_data_piutang',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='obj_data_piutang_nominal',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='obj_pelunasan_piutang',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='obj_pelunasan_piutang_persen',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='pelunasan_piutang_persen',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='pelunasan_piutang_rupiah',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='penelitian_ulang',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb',
            name='uppd',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb_detail',
            name='id_pkb',
        ),
        migrations.RemoveField(
            model_name='bab3_bbnkb_detail',
            name='id_pkb_detail',
        ),
        migrations.AddField(
            model_name='bab3_bbnkb_detail',
            name='id_bbnkb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab3_bbnkb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bab3_bbnkb_detail',
            name='id_bbnkb_detail',
            field=models.CharField(default='1b18ef4a-7940-4503-9202-b31bb1488dfb', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='d167603e-84bc-4bae-bfad-1c0061d85193', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='b0c09aa7-4471-4f49-9d13-bcec669b55d2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='0b0854a5-0726-4492-aced-20f3a0bd8fdd', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='fbb80bdd-a8f7-436b-abf6-0f1dcc9fb4dd', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='a228d7e5-4827-4377-b543-ac662f10a23c', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='d6fa8810-d50f-4231-b914-1dd7a7dcb854', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='dff9e7ec-68fd-4a4a-a02f-e75180bfcfbe', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='ee20053b-3b66-4c4c-8b9d-fe32e4fcdb59', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='d5a07e76-f378-4971-8eea-5d0bf7bf0a3d', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='7bbe6a06-e358-4c12-9a81-dfb296f35502', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='20500c0f-153c-49cd-bef6-2d0abb42ee34', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_bbnkb',
            name='id_bbnkb',
            field=models.CharField(default='d7ae31e3-1963-44ea-9926-da3e22ef9686', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='id_pkb',
            field=models.CharField(default='cf914a9d-8ec1-418a-b3cf-71a4fc026dae', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_pkb_detail',
            name='id_pkb_detail',
            field=models.CharField(default='4465a075-9906-4dc0-90dc-58bfea6ae0a5', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='f5e1cce4-0bb0-4c7b-997d-0356d293cb29', max_length=36, primary_key=True, serialize=False),
        ),
    ]
