# Generated by Django 5.0.6 on 2024-06-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0015_alter_headerlhe_id_lhe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerlhe',
            name='id_lhe',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x000001D06A479120>', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='01afbae0-5404-4cef-9764-4ddc21da3a3b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab2_sasaran_evaluasi_pembinaan',
            fields=[
                ('id_sasaran', models.CharField(default='b86ce285-4e47-4557-92c6-e79fdbc69bd4', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
        migrations.CreateModel(
            name='bab2_tujuan_evaluasi_pembinaan',
            fields=[
                ('id_tujuan', models.CharField(default='51662305-8365-4161-adf5-2ea499f94a23', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
        ),
    ]
