# Generated by Django 5.0.6 on 2024-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0016_alter_headerlhe_id_lhe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerlhe',
            name='periode_akhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerlhe',
            name='periode_awal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='e5f25039-dbfb-4a62-9b05-6a5525ad0768', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='ffdcef90-e2b6-4733-9374-68ef29aa79c7', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kepegawaianlhe',
            name='id_kepegawaian',
            field=models.CharField(default='<function uuid4 at 0x0000028B206D9120>', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='fb8933ae-8165-4dd7-b720-9342d657f6bb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
