# Generated by Django 5.0.6 on 2024-06-16 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0018_remove_kepegawaianlhe_id_lhe_and_more'),
        ('surat_tugas', '0017_alter_trxsurattugas_id_surat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            old_name='detail',
            new_name='golongan',
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='89894cd6-a455-42a5-b31f-a9e7f849e381', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='a28b8dbb-a192-46af-bfbd-5ec9e8cc3379', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='10e82c7f-a9ba-4142-8079-ed20e768f65a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='51f1731b-ba4f-4323-ae16-558c41e11908', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='120b6a50-7b25-4be3-b64e-1ec4438ccefa', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='8d54aeca-7b99-4546-a6b8-f0ea4f08db70', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_kepegawaian_normatif',
            fields=[
                ('id_tu_kepegawaian_normatif', models.CharField(default='78f0cfa6-b0db-4030-bee1-9102200f1a54', max_length=36, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_tu_kepegawaian', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.bab2_tatausaha_kepegawaian')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.masterjabatan')),
            ],
        ),
    ]
