# Generated by Django 5.0.6 on 2024-06-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0019_rename_detail_bab2_tatausaha_kepegawaian_detail_golongan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='fc1b2ef0-e31d-4a78-8a85-e3f6bdc832e7', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='f3b3a530-dfd3-47eb-91a9-84db4c8ac418', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='1a835320-cb2d-4167-af8e-d0339925921b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='b3b0b47a-a0ba-407a-8af3-c9d8e9b658c3', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='96a5f57c-280c-49b4-b2ff-23a2b4ee0b20', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='a17eb449-89a7-42fb-bdb0-d7bc742810fb', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='7d135478-27a3-45bc-b9bf-6f4910f0c13b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bab2_data_umum',
            unique_together={('id_data_umum', 'detail')},
        ),
    ]
