# Generated by Django 5.0.6 on 2024-06-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0020_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bab2_data_umum',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='f4adc6f9-b970-42a7-a999-7015a0bf18ea', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='dbb391b7-1679-4b7c-a646-a8a06ad7b130', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='6f7f97ae-7902-4311-85a6-17fd2dd62c90', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='5debeae1-644e-4789-96a6-fb40bd0a6d0e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='2853cbab-1bd4-41d3-b9d7-240e270e802f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='f9faade9-55e6-4a50-afa0-513f8b1d9637', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='13e57c56-e706-4e06-a09e-351ed1b49b68', max_length=36, primary_key=True, serialize=False),
        ),
    ]
