# Generated by Django 5.0.6 on 2024-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0020_bab3_pap_is_periode1_bab3_pap_is_periode2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bab3_pap_tahun1',
            name='tahun',
            field=models.SmallIntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='bab3_pap_tahun2',
            name='tahun',
            field=models.SmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='441851bf-64cd-4d08-80fa-2ecd10cb3ebe', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='de1109fe-b795-47b1-8ced-05096be36528', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='24626038-f00a-475d-a966-e85b17a7347e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='17c9aff4-c450-4534-93b4-f616a24ad72e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='4e56ada7-2ed1-4295-9097-e43acfad6c13', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='430c8aba-90bd-4488-9726-db36170936b2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='e1336492-e4d9-4b89-8429-6b810d2e8764', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='d951012e-b1a8-429e-91fd-f446c9e17d70', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='46e51da8-74fc-4a8d-aad4-4d4ea31a82d0', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='0792e4ce-bdd2-4348-b272-9ef8ec7bcf5f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='34991bf7-9f3e-474e-81d8-ebb429863375', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_bbnkb',
            name='id_bbnkb',
            field=models.CharField(default='af901cae-1e11-4cd3-8425-5be0f501a3ca', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_bbnkb_detail',
            name='id_bbnkb_detail',
            field=models.CharField(default='d09d6479-8b3d-401e-bcaf-6d2836e05cf3', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pap',
            name='id_pap',
            field=models.CharField(default='05434065-89c4-4191-9e1f-047815099a38', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_pap_tahun1',
            name='id_pap_tahun1',
            field=models.CharField(default='b5f447db-9d03-47b3-9755-2c6b48035813', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pap_tahun2',
            name='id_pap_tahun2',
            field=models.CharField(default='c6e440f8-ea37-4b1d-9aac-baca35c21af6', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='id_pkb',
            field=models.CharField(default='cb7b009f-0aac-43b1-a8b6-6d8364efc1c0', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_pkb_detail',
            name='id_pkb_detail',
            field=models.CharField(default='141ae0cf-3d8f-4cd0-ba4c-4e3148454de7', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='18c8af6d-6f25-4351-9420-9e8fb98ed4bb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
