# Generated by Django 5.0.6 on 2024-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0021_alter_bab2_data_umum_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='115eb53e-0e2e-4eef-8630-b0ee47587f97', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='f941eddc-7d99-4236-a469-bf2cbeb3912f', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='317db603-27be-4a24-8835-9f3df5878fec', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='86b87848-ae48-4bea-9637-ecc209eea084', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='b6cb3d85-f183-4bbe-a4c4-ed97bca4d369', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='1b05aa56-b425-4563-8dbc-864247e25e24', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='67910a64-4594-47d4-a62a-3da8f8ba0724', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bab2_sasaran_evaluasi_pembinaan',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_kepegawaian_detail',
            unique_together={('id_tu_kepegawaian', 'golongan')},
        ),
        migrations.AlterUniqueTogether(
            name='bab2_tatausaha_kepegawaian_normatif',
            unique_together={('id_tu_kepegawaian', 'nama', 'nip')},
        ),
        migrations.AlterUniqueTogether(
            name='bab2_tujuan_evaluasi_pembinaan',
            unique_together={('id_lhe', 'detail')},
        ),
        migrations.AlterUniqueTogether(
            name='simpulanhasilvalbin',
            unique_together={('id_lhe', 'detail')},
        ),
    ]
