# Generated by Django 5.0.6 on 2024-06-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0022_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='d6e828e2-7627-4a98-b97d-468848cc3a92', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='88a2fe4d-4bb4-47ec-9af7-825ed195e69e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='20ddf047-7fdc-4c39-b4ea-0eafab8b1d66', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='f32c6b02-a774-4dda-89f1-6d655f5bef28', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='e3153aa4-c35a-4877-92c7-12dab3440de5', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='fad2d6dc-df52-466e-b256-f9a951fbeec0', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='46502d34-4fb5-4af5-ae85-824112516ec2', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='bab2_tatausaha_keuangan',
            fields=[
                ('id_tu_keuangan', models.CharField(default='93ca68a2-6c60-4b91-bf3c-5751080fcc80', max_length=36, primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('id_lhe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='lhe.headerlhe')),
            ],
            options={
                'unique_together': {('id_tu_keuangan', 'detail')},
            },
        ),
    ]
