# Generated by Django 5.0.7 on 2024-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lhe', '0027_alter_bab2_data_umum_id_data_umum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bab2_data_umum',
            name='id_data_umum',
            field=models.CharField(default='845c7c36-3503-4b7b-bf5a-e438f0a7095a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_sasaran_evaluasi_pembinaan',
            name='id_sasaran',
            field=models.CharField(default='f551d391-85b1-406e-b06e-535ed5146753', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_bangun_tanah',
            name='id_tu_bagun_tanah',
            field=models.CharField(default='ef7a9891-a9db-4eba-bda5-c067cead8411', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian',
            name='id_tu_kepegawaian',
            field=models.CharField(default='19a0cec1-3d6e-441a-ad14-c1032336d610', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_detail',
            name='id_tu_kepegawaian_detail',
            field=models.CharField(default='8e29799f-268c-4c18-a523-9d606ce69a5e', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_kepegawaian_normatif',
            name='id_tu_kepegawaian_normatif',
            field=models.CharField(default='a5c8a9da-f5e2-46a4-8a09-896cacfff808', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_keuangan',
            name='id_tu_keuangan',
            field=models.CharField(default='4c417ad1-cc69-4e11-baef-5bd09ec00a78', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemkab',
            name='id_tu_mobil_pemkab',
            field=models.CharField(default='70f3ed76-38d8-4e61-8b5d-b1199e98aca5', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_mobil_pemprov',
            name='id_tu_mobil_pemprov',
            field=models.CharField(default='37865fc7-03c3-40c2-b8ba-ec75bc45228b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tatausaha_motor_pemprov',
            name='id_tu_motor_pemprov',
            field=models.CharField(default='9d14a330-7e60-4731-96de-7118b9df7064', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab2_tujuan_evaluasi_pembinaan',
            name='id_tujuan',
            field=models.CharField(default='d5e6863b-6beb-4592-bb48-5a865323d52a', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_bbnkb',
            name='id_bbnkb',
            field=models.CharField(default='62a64523-ec32-45df-a0cd-6fe2e5d7a647', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_bbnkb_detail',
            name='id_bbnkb_detail',
            field=models.CharField(default='60dbb641-9c8b-4384-a59a-f46787b12d57', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pap',
            name='id_pap',
            field=models.CharField(default='6ee44ee8-85c1-4058-9f00-77a5515dffb6', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_pap_tahun1',
            name='id_pap_tahun1',
            field=models.CharField(default='85f47a5f-188b-4388-ac60-aea8cb3b1427', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pap_tahun2',
            name='id_pap_tahun2',
            field=models.CharField(default='4cb27edb-d208-4fef-8729-fcb8819e7954', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bab3_pkb',
            name='id_pkb',
            field=models.CharField(default='15aca0a5-32ba-483a-b429-40f87c0fe985', max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bab3_pkb_detail',
            name='id_pkb_detail',
            field=models.CharField(default='22db1b6c-9846-434d-a6cf-d12228e8e1f8', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='simpulanhasilvalbin',
            name='id_simpulan',
            field=models.CharField(default='52f4655e-60c0-48e4-b9c3-967dc7e90968', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='bab3_pap',
            unique_together={('id_lhe',)},
        ),
    ]
