# Generated by Django 5.0.6 on 2024-06-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surat_tugas', '0015_alter_st_dasartugas_dasar_tugas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrxResume',
            fields=[
                ('id_resume', models.CharField(default='9724dadf-22a5-4556-8d4a-4a1519ab2deb', max_length=36, primary_key=True, serialize=False)),
                ('updatedBy', models.CharField(max_length=50)),
                ('updatedAt', models.DateField(blank=True, null=True)),
                ('createdBy', models.CharField(max_length=50)),
                ('createdAt', models.DateField(auto_now_add=True, null=True)),
                ('suratTugas', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surat_tugas.trxsurattugas')),
            ],
        ),
    ]
