# Generated by Django 5.0.6 on 2024-06-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='f144b68b-0176-42dd-accf-25f434f2f0c2', max_length=36, primary_key=True, serialize=False),
        ),
    ]
