# Generated by Django 5.0.6 on 2024-06-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='1d5f843a-d9c5-49ff-8ba4-48e4821953a5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
