# Generated by Django 5.0.6 on 2024-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='3c97f25e-660a-4f16-b981-af80283a437d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
