# Generated by Django 5.0.6 on 2024-06-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='6f7450d7-878e-447b-968b-f2dfa7221757', max_length=36, primary_key=True, serialize=False),
        ),
    ]
