# Generated by Django 5.0.6 on 2024-06-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='c370dcb3-07e2-4363-8966-b3a3cc482a72', max_length=36, primary_key=True, serialize=False),
        ),
    ]
