# Generated by Django 5.0.6 on 2024-06-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='e605edf7-5819-495f-9471-d80bda8c5366', max_length=36, primary_key=True, serialize=False),
        ),
    ]
