# Generated by Django 5.0.6 on 2024-06-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='4dc2a332-3ff0-46b1-8a06-756380cd58c2', max_length=36, primary_key=True, serialize=False),
        ),
    ]
