# Generated by Django 5.0.6 on 2024-06-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='d993bc05-9647-40e0-aff1-6e3213fe1018', max_length=36, primary_key=True, serialize=False),
        ),
    ]
