# Generated by Django 5.0.6 on 2024-06-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='65e94f59-53a9-4c6d-aa92-d31157cebd91', max_length=36, primary_key=True, serialize=False),
        ),
    ]
