# Generated by Django 5.0.6 on 2024-06-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='b470fb38-79d8-41a3-a059-9caa5b11db57', max_length=36, primary_key=True, serialize=False),
        ),
    ]
