# Generated by Django 5.0.6 on 2024-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='3651bae0-320e-40e0-bfc5-5475955dd393', max_length=36, primary_key=True, serialize=False),
        ),
    ]
