# Generated by Django 5.0.6 on 2024-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='e0ac61b0-5e02-4c5f-b74d-a31e8fec328e', max_length=36, primary_key=True, serialize=False),
        ),
    ]
