# Generated by Django 5.0.6 on 2024-06-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='f9280880-3474-4629-913c-3cbe0ee5be78', max_length=36, primary_key=True, serialize=False),
        ),
    ]
