# Generated by Django 5.0.6 on 2024-06-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='9310df01-0a57-4071-ae74-fa165e703c51', max_length=36, primary_key=True, serialize=False),
        ),
    ]
