# Generated by Django 5.0.6 on 2024-06-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='7a418e71-3419-4fb7-a12a-af69a15e0484', max_length=36, primary_key=True, serialize=False),
        ),
    ]
