# Generated by Django 5.0.6 on 2024-06-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0022_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='438d10c6-27bf-4361-bbc7-cfae0ed61ca5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
