# Generated by Django 5.0.6 on 2024-06-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0023_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='3aa413d8-9aff-4708-949b-e3468285c6b2', max_length=36, primary_key=True, serialize=False),
        ),
    ]
