# Generated by Django 5.0.6 on 2024-06-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0025_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='0e225b8a-e22d-4006-ae92-39ff0aabf3a2', max_length=36, primary_key=True, serialize=False),
        ),
    ]
