# Generated by Django 5.0.6 on 2024-06-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0027_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='46892c96-3e52-41a4-92f2-e0efc0a86e82', max_length=36, primary_key=True, serialize=False),
        ),
    ]
