# Generated by Django 5.0.6 on 2024-06-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0028_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='755a053c-51f9-4e08-a008-faeea5be5b78', max_length=36, primary_key=True, serialize=False),
        ),
    ]
