# Generated by Django 5.0.6 on 2024-06-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0029_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='582e6df1-f87b-4ff5-9d66-1ea0ea81149d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
