# Generated by Django 5.0.6 on 2024-06-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0030_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='43c4fa8f-7578-44a0-b996-1e9f8e6d19cf', max_length=36, primary_key=True, serialize=False),
        ),
    ]
