# Generated by Django 5.0.6 on 2024-07-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0033_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='5a119f22-948a-4fe7-b3bd-5e7e166a4759', max_length=36, primary_key=True, serialize=False),
        ),
    ]
