# Generated by Django 5.0.6 on 2024-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0034_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='b9912edf-837c-4d69-8e4e-cf36cdf33773', max_length=36, primary_key=True, serialize=False),
        ),
    ]
