# Generated by Django 5.0.6 on 2024-07-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0035_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='65f91095-79c9-449d-8b01-aebc2db291e7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
