# Generated by Django 5.0.6 on 2024-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0036_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='66e39762-8cf9-426a-a78b-1939969b06b0', max_length=36, primary_key=True, serialize=False),
        ),
    ]
