# Generated by Django 5.0.6 on 2024-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0039_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='f3cb2202-9ccf-49af-bc03-11b95c78aae2', max_length=36, primary_key=True, serialize=False),
        ),
    ]
