# Generated by Django 5.0.6 on 2024-07-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0040_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='b1a246ca-0f3a-497f-b357-1f01468b7439', max_length=36, primary_key=True, serialize=False),
        ),
    ]
