# Generated by Django 5.0.6 on 2024-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0041_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='ed2f9670-f845-441f-b9e0-b6974f87d389', max_length=36, primary_key=True, serialize=False),
        ),
    ]
