# Generated by Django 5.0.6 on 2024-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0042_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='5c000949-8b28-48f4-bad1-b3e8a9e61f92', max_length=36, primary_key=True, serialize=False),
        ),
    ]
