# Generated by Django 5.0.6 on 2024-07-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0043_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='557a7fb7-c476-40da-b4e0-e995e269824b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
