# Generated by Django 5.0.6 on 2024-07-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0044_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='13c81358-0d03-4682-b2f0-0a2144ee2068', max_length=36, primary_key=True, serialize=False),
        ),
    ]
