# Generated by Django 5.0.6 on 2024-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0045_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='f3494e7e-9e23-4bf6-ac73-d4603091ceec', max_length=36, primary_key=True, serialize=False),
        ),
    ]
