# Generated by Django 5.0.6 on 2024-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0046_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='b9d56c78-b9e1-4dca-9c87-a261e68e1a99', max_length=36, primary_key=True, serialize=False),
        ),
    ]
