# Generated by Django 5.0.6 on 2024-07-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0047_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='5825b3ff-202e-4f36-be37-18a4c0772fe9', max_length=36, primary_key=True, serialize=False),
        ),
    ]
