# Generated by Django 5.0.6 on 2024-07-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0050_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='6cf6c3b6-31e5-4d87-add6-3acdc4d7c9e0', max_length=36, primary_key=True, serialize=False),
        ),
    ]
