# Generated by Django 5.0.7 on 2024-07-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0053_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='097eba1a-27ed-4438-9b08-8e0989b35531', max_length=36, primary_key=True, serialize=False),
        ),
    ]
