# Generated by Django 5.0.7 on 2024-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0055_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='b6178c18-c646-4417-b93b-bceb5208be63', max_length=36, primary_key=True, serialize=False),
        ),
    ]
