# Generated by Django 5.0.7 on 2024-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0056_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='52998fdc-2714-438d-a93c-4e99979011eb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
