# Generated by Django 5.0.7 on 2024-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0057_alter_trxresume_id_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trxresume',
            name='id_resume',
            field=models.CharField(default='cba1335d-e287-415b-8207-86c792a8052d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
